IF OBJECT_ID( 'TEMPDB..#TEMP01' )  IS NOT NULL BEGIN DROP TABLE #TEMP01 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP02' )  IS NOT NULL BEGIN DROP TABLE #TEMP02 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP03' )  IS NOT NULL BEGIN DROP TABLE #TEMP03 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP04' )  IS NOT NULL BEGIN DROP TABLE #TEMP04 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP05' )  IS NOT NULL BEGIN DROP TABLE #TEMP05 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP06' )  IS NOT NULL BEGIN DROP TABLE #TEMP06 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP07' )  IS NOT NULL BEGIN DROP TABLE #TEMP07 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP08' )  IS NOT NULL BEGIN DROP TABLE #TEMP08 END ;
IF OBJECT_ID( 'TEMPDB..#TEMP09' )  IS NOT NULL BEGIN DROP TABLE #TEMP09 END ;

---------1.取客户积分获取比例  #TEMP01----
SELECT T1.[COMPANY_ABBREVIATION]
      ,T1.[MEMBER_CODE]
      ,T1.[PRESENT_INTEGRAL]
      ,T1.[ID]
	  ,T2.PROPORTION
INTO #TEMP01
FROM [EBS_CUSTOMER_MEMBER] T1 WITH (NOLOCK)
INNER JOIN [EBS_POINTS_OBTAIN_RULE_BASE] T2 WITH (NOLOCK)
ON T1.MEMBER_CODE=T2.MEMBER_CODE
;

---------2.取以前剩余核销金额  #TEMP02----
SELECT *
,[VERIFICATION_AMOUNT]-[SUM_POINTS_AMT] AS BALANCE_AMT
INTO #TEMP02
FROM (
SELECT [COMPANY_ABBREVIATION]    AS [COMPANY_ABBREVIATION]
      ,SUM([CHARGE_AMOUNT])		 AS [CHARGE_AMOUNT]
      ,SUM([VERIFICATION_AMOUNT])AS [VERIFICATION_AMOUNT]
      ,SUM([POINTS_NUM]*ISNULL([PROPORTION],0)) AS [SUM_POINTS_AMT]
FROM [EBS_VERIFICATION_INCOME_LOG] WITH (NOLOCK)
WHERE [INCOME_ID] IS NOT NULL
GROUP BY [COMPANY_ABBREVIATION]
) T1
;

---------3.计算本次待处理的核销累计金额  #TEMP03----
SELECT TT1.[ID]
      ,TT1.[WAYBILL_NUM]
      ,TT1.[WAYBILL_ID]
      ,TT1.[COMPANY_ABBREVIATION]
      ,TT1.[CHARGE_AMOUNT]
      ,TT1.[VERIFICATION_AMOUNT]
      ,TT1.[INCOME_ID]
	  ,TT1.[SUM_VERIFICATION_AMOUNT]  ----待处理的核销累计金额
	  ,CASE WHEN TT1.[VERIFICATION_AMOUNT]<=0     THEN NULL 
	        WHEN TT1.[SUM_VERIFICATION_AMOUNT]<=0 THEN NULL
	        WHEN TT1.[ID]=0                       THEN NULL
	        ELSE TT1.PROPORTION END AS PROPORTION      ----积分获取比例
INTO #TEMP03
FROM (
SELECT T1.[ID]
      ,T1.[WAYBILL_NUM]
      ,T1.[WAYBILL_ID]
      ,T1.[COMPANY_ABBREVIATION]
      ,T1.[CHARGE_AMOUNT]
      ,T1.[VERIFICATION_AMOUNT]
      ,T1.[INCOME_ID]
	  ,SUM(T1.[VERIFICATION_AMOUNT]) OVER(PARTITION BY T1.[COMPANY_ABBREVIATION] ORDER BY T1.[ID]) AS [SUM_VERIFICATION_AMOUNT]  ----待处理的核销累计金额
	  ,CASE WHEN T1.[VERIFICATION_AMOUNT]<=0 THEN NULL ELSE T2.PROPORTION END AS PROPORTION                                      ----积分获取比例
FROM (
SELECT 0    AS [ID]          -----以前剩余的核销定义ID=0，作为起点
      ,NULL AS [WAYBILL_NUM]
      ,NULL AS [WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,BALANCE_AMT AS [CHARGE_AMOUNT]
      ,BALANCE_AMT AS [VERIFICATION_AMOUNT]
      ,NULL  AS [INCOME_ID]
FROM #TEMP02      ----前期剩余核销金额
UNION ALL
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
      ,[INCOME_ID]
FROM [EBS_VERIFICATION_INCOME_LOG] WITH (NOLOCK)    ----本次计算的核销记录
WHERE [INCOME_ID] IS NULL
) T1
LEFT OUTER JOIN #TEMP01 T2 ON T1.COMPANY_ABBREVIATION=T2.COMPANY_ABBREVIATION
) TT1


---------4.取应该参与积分计算的记录  #TEMP04----
-----4.1 不包括以前剩余的记录 #TEMP02
-----4.2 累计核销金额>0
-----4.3 当前记录的累计核销金额>以前记录的累计核销金额的最大值
SELECT *
INTO #TEMP04
FROM (
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
      ,[INCOME_ID]
	  ,[SUM_VERIFICATION_AMOUNT]  
	  ,PROPORTION      
	  ,DENSE_RANK() OVER(ORDER BY [COMPANY_ABBREVIATION]) AS COMPANY_NO              ----按客户排序
	  ,ROW_NUMBER() OVER(PARTITION BY [COMPANY_ABBREVIATION] ORDER BY ID) AS ROW_NO  ----同一客户 按ID排序
      ,ISNULL(MAX([SUM_VERIFICATION_AMOUNT]) OVER(PARTITION BY [COMPANY_ABBREVIATION] ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),0) AS [MAX_SUM_VERIFICATION_AMOUNT] --前面记录最大核销金额
FROM #TEMP03
)  T1
WHERE ID>0                        ----以前剩余
AND [SUM_VERIFICATION_AMOUNT]>0   ----累计核销金额>0
AND [SUM_VERIFICATION_AMOUNT]>[MAX_SUM_VERIFICATION_AMOUNT] ---当前累计核销金额>之前累计核销金额最大值
ORDER BY COMPANY_NO,ROW_NO

---------5.计算应获取积分、用掉的核销金额和剩余金额  #TEMP04----
---------5.1根据累计核销金额计算累计积分 
---------5.2取前一记录的累计积分 
---------5.3当前累计积分-前一记录的累计积分=当前记录应获取的积分 
SELECT *
      ,SUM_POINTS-PRE_SUM_POINTS              AS [POINTS_NUM]               ----计算应获取积分
      ,(SUM_POINTS-PRE_SUM_POINTS)*PROPORTION AS [USE_VERIFICATION_AMOUNT]  ----积分用掉的核销金额
      ,[VERIFICATION_AMOUNT]- (SUM_POINTS-PRE_SUM_POINTS)*PROPORTION AS [SURPLUS_AMOUNT]   ----剩余金额
INTO #TEMP05
FROM(
SELECT *
,ISNULL(LAG(SUM_POINTS) OVER(PARTITION BY [COMPANY_ABBREVIATION] ORDER BY ID),0) AS PRE_SUM_POINTS  ----前一纪录累计应获取积分
FROM (
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
      ,[INCOME_ID]
	  ,[SUM_VERIFICATION_AMOUNT]
	  ,PROPORTION
	  ,COMPANY_NO
	  ,ROW_NO
	  ,FLOOR([SUM_VERIFICATION_AMOUNT]/PROPORTION) AS SUM_POINTS     ----本次待处理的累计应获取累计积分
FROM #TEMP04
) T1
) T2


------6.合并数据集，返回总的结果
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
	  ,[SUM_VERIFICATION_AMOUNT]
      ,[INCOME_ID]
      ,[SURPLUS_AMOUNT]
      ,[POINTS_NUM]
      ,[PROPORTION]
--INTO #TEMP06
FROM (
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
	  ,[SUM_VERIFICATION_AMOUNT]
      ,[INCOME_ID]
      ,NULL AS [SURPLUS_AMOUNT]
      ,NULL AS [POINTS_NUM]
      ,NULL AS [PROPORTION]
FROM #TEMP03
WHERE [ID] NOT IN (
SELECT [ID] FROM #TEMP05   ------补齐未参加计算的记录
)
AND ID>0
UNION ALL
SELECT [ID]
      ,[WAYBILL_NUM]
      ,[WAYBILL_ID]
      ,[COMPANY_ABBREVIATION]
      ,[CHARGE_AMOUNT]
      ,[VERIFICATION_AMOUNT]
	  ,[SUM_VERIFICATION_AMOUNT]
      ,[INCOME_ID]
      ,[SURPLUS_AMOUNT]
      ,[POINTS_NUM]
      ,[PROPORTION]
FROM #TEMP05
) T1
ORDER BY [COMPANY_ABBREVIATION],ID


SELECT * FROM #TEMP01
SELECT * FROM #TEMP02
SELECT * FROM #TEMP03
SELECT * FROM #TEMP04
SELECT * FROM #TEMP05
SELECT * FROM #TEMP06

